host: ""
queryport: ""
voiceport: ""
username: ""
password: ""
nick: ""
channel: ""
bbcodes_to_remove:
    - "size"
    - "font"
    - "highlight"
    - "left"
    - "right"
    - "center"
    - "indent"
    - "email"
    - "url"
    - "thread"
    - "post"
    - "list"
    - "img"
    - "video"
    - "php"
    - "html"
    - "quote"
    - "noparse"
    - "attach"
    - "search"